- hosts: all
  become: True
  gather_facts: yes
  any_errors_fatal: true
  tasks:
    - name: Include play for lvextend on existing disks.
      include: existing_lvextend.yml
      when:
        - ansible_virtualization_role == "guest"
        - ansible_virtualization_type == "VMware" or "virtualbox"
        - ansible_os_family == "RedHat"
      tags: [ 'never', 'existing_disk' ]

    - name: Include play for lvextend using new disks.
      include: newdisk_lvextend.yml
      when: 
        - ansible_virtualization_role == "guest"
        - ansible_virtualization_type == "VMware" or "virtualbox"
        - ansible_os_family == "RedHat"
      tags: [ 'never', 'new_disk' ]
